version: '3.8'
services:
  # main:
  #   container_name: main
  #   build: 
  #     context: .
  #   env_file:
  #     - .env
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   ports:
  #     - 3000:3000
  #   command: npm run start:dev
  #   depends_on:
  #     - db
  #   restart: always
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test-task
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root  
    ports:
      - "5050:80"

volumes:
  postgres: